class_name LangEN
extends RefCounted

## 영어 번역 표 — 한국어 원문(코드·데이터의 리터럴과 바이트 단위 일치) → 영어.
## ⚠️ tools/gen_lang_en.py 가 생성한다. 손으로 고칠 땐 값(영어)만 고치고 키는 절대 건드리지 말 것
## (키가 원문과 1글자라도 다르면 그 문구는 조용히 한국어로 남는다). 항목 수: 875

const TABLE: Dictionary = {
	"\n\n거두어 함께 걷던 %d명도\n여기서 걸음을 멈췄다.": "\n\nThe %d they took in stop walking here as well.",
	"\n\n거두어 함께 걷던 한 사람도\n여기서 걸음을 멈췄다.": "\n\nThe one they took in stops walking here as well.",
	"\n곁의 표식: [ %s ]": "\nA marker beside it: [ %s ]",
	"\n이제 행렬은 %d명이다.": "\nThe column is down to %d.",
	"  · 짐이 가벼워 먼 길에서 물 -%d": "  · light load, water -%d on the long road",
	"  · 짐이 무거워 걸음마다 물 +%d": "  · heavy load, water +%d each step",
	" 갈증이었다.": " It was thirst.",
	" 식량이 없었다.": " There was no food.",
	"%d번": "%d",
	"%d번째 원정": "Expedition %d",
	"%d번째 원정 · %d걸음 · 행렬 %d명\n걸음마다 물 %d · 식량 %s": "Expedition %d · step %d · column of %d\nEach step: water %d · food %s",
	"%d번째 원정 · %s\n    %s에서 %d걸음째 스러졌다.%s": "Expedition %d · %s\n    Perished at %s, %d steps in.%s",
	"%d번째 원정 · %s\n    건너편에서 모두와 다시 만났다.": "Expedition %d · %s\n    On the other side, they met everyone again.",
	"%d번째 원정 · %s\n    기록이 모래에 지워졌다.": "Expedition %d · %s\n    The record was erased by the sand.",
	"%d번째 원정 · %s\n    끝에 닿았다. 다음 원정대가 이곳으로 온다.": "Expedition %d · %s\n    Reached the end. The next expedition will come to this place.",
	"%d번째 원정 · %s\n    아직 길 위에 있다.": "Expedition %d · %s\n    Still on the road.",
	"%d번째 원정대가 떠날 채비를 한다.": "Expedition %d makes ready to set out.",
	"%d회": "%d",
	"%s\n\n남긴 것: %s": "%s\n\nLeft behind: %s",
	"%s\n\n남긴 것: %s  [ %s ]": "%s\n\nLeft behind: %s  [ %s ]",
	"%s   (%s 부족)": "%s   (short of %s)",
	"%s   (%s 필요)": "%s   (needs %s)",
	"%s   (가진 것 부족)": "%s   (not enough on hand)",
	"%s  (다시 눌러서 제거)": "%s  (tap again to remove)",
	"%s %s 원정대": "%s %s Expedition",
	"%s %s의 %s": "%s %s's %s",
	"%s -%d · 보유 %d": "%s -%d · have %d",
	"%s · 아직 소식이 없다": "%s · no word yet",
	"%s 곁에 한두 마디. 다음 원정대가 읽는다.": "A word or two beside the %s. The next expedition will read them.",
	"AI 생성 · 직접 골라 다듬음": "AI-generated · picked and refined by hand",
	"Godot Engine · MIT 라이선스": "Godot Engine · MIT license",
	"[color=#35667f]물[/color]은 걸음마다,\n[color=#8c5f16]식량[/color]은 두 걸음마다 줄어든다.\n[color=#7a4a1e]로프[/color]는 갈라진 틈을 건너게 하고,\n[color=#4d5a26]장막[/color]은 폭풍을 버티게 한다.": "[color=#35667f]Water[/color] drops every step, [color=#8c5f16]food[/color] every second step. [color=#7a4a1e]Rope[/color] takes you across the cracks, and a [color=#4d5a26]tarp[/color] lets you ride out the storm.",
	"[color=#8a2f1b]%s[/color] · 마을에 있다": "[color=#8a2f1b]%s[/color] · in the village",
	"res://assets/arts/01_지도_양피지.png": "res://assets/arts/01_지도_양피지.png",
	"res://assets/arts/13_단면_마을.png": "res://assets/arts/13_단면_마을.png",
	"res://assets/arts/14_단면_폐허.png": "res://assets/arts/14_단면_폐허.png",
	"res://assets/arts/15_단면_갈라진바닥.png": "res://assets/arts/15_단면_갈라진바닥.png",
	"res://assets/arts/16_단면_모래폭풍.png": "res://assets/arts/16_단면_모래폭풍.png",
	"res://assets/arts/17_단면_재앙의자리.png": "res://assets/arts/17_단면_재앙의자리.png",
	"res://assets/arts/18_단면_사막.png": "res://assets/arts/18_단면_사막.png",
	"res://assets/arts/22_배경_가방.png": "res://assets/arts/22_배경_가방.png",
	"res://assets/arts/23_배경_공통.png": "res://assets/arts/23_배경_공통.png",
	"res://assets/arts/23_배경_공통_가로.png": "res://assets/arts/23_배경_공통_가로.png",
	"res://assets/arts/24_오프닝_떠난다.png": "res://assets/arts/24_오프닝_떠난다.png",
	"res://assets/arts/24_오프닝_떠난다_가로.png": "res://assets/arts/24_오프닝_떠난다_가로.png",
	"res://assets/arts/25_오프닝_죽는다.png": "res://assets/arts/25_오프닝_죽는다.png",
	"res://assets/arts/25_오프닝_죽는다_가로.png": "res://assets/arts/25_오프닝_죽는다_가로.png",
	"res://assets/arts/26_오프닝_지운다.png": "res://assets/arts/26_오프닝_지운다.png",
	"res://assets/arts/26_오프닝_지운다_가로.png": "res://assets/arts/26_오프닝_지운다_가로.png",
	"res://assets/arts/27_오프닝_보내는자.png": "res://assets/arts/27_오프닝_보내는자.png",
	"res://assets/arts/27_오프닝_보내는자_가로.png": "res://assets/arts/27_오프닝_보내는자_가로.png",
	"res://assets/arts/28_오프닝_남긴다.png": "res://assets/arts/28_오프닝_남긴다.png",
	"res://assets/arts/28_오프닝_남긴다_가로.png": "res://assets/arts/28_오프닝_남긴다_가로.png",
	"res://assets/arts/29_타이틀_키아트.png": "res://assets/arts/29_타이틀_키아트.png",
	"res://assets/arts/29_타이틀_키아트_가로.png": "res://assets/arts/29_타이틀_키아트_가로.png",
	"res://assets/arts/39_배경_창고_가로.png": "res://assets/arts/39_배경_창고_가로.png",
	"res://assets/arts/47_엔딩순환_도착.png": "res://assets/arts/47_엔딩순환_도착.png",
	"res://assets/arts/48_엔딩순환_밀어냄.png": "res://assets/arts/48_엔딩순환_밀어냄.png",
	"res://assets/arts/49_엔딩순환_이어짐.png": "res://assets/arts/49_엔딩순환_이어짐.png",
	"res://assets/arts/50_엔딩재회_닿음.png": "res://assets/arts/50_엔딩재회_닿음.png",
	"res://assets/arts/51_엔딩재회_지나쳐.png": "res://assets/arts/51_엔딩재회_지나쳐.png",
	"res://assets/arts/52_엔딩재회_모두.png": "res://assets/arts/52_엔딩재회_모두.png",
	"res://assets/arts/55_막간_폭풍.png": "res://assets/arts/55_막간_폭풍.png",
	"res://assets/arts/56_막간_고요.png": "res://assets/arts/56_막간_고요.png",
	"res://assets/arts/57_막간_채비.png": "res://assets/arts/57_막간_채비.png",
	"res://assets/arts/72_단면_마른강.png": "res://assets/arts/72_단면_마른강.png",
	"res://assets/arts/73_단면_버려진야영지.png": "res://assets/arts/73_단면_버려진야영지.png",
	"res://assets/arts/74_단면_오아시스.png": "res://assets/arts/74_단면_오아시스.png",
	"res://assets/arts/75_단면_뼈의들판.png": "res://assets/arts/75_단면_뼈의들판.png",
	"res://assets/arts/76_단면_독웅덩이.png": "res://assets/arts/76_단면_독웅덩이.png",
	"res://assets/arts/77_단면_모래의벽.png": "res://assets/arts/77_단면_모래의벽.png",
	"res://assets/arts/78_단면_무너진담.png": "res://assets/arts/78_단면_무너진담.png",
	"res://assets/arts/79_단면_폭풍의문.png": "res://assets/arts/79_단면_폭풍의문.png",
	"res://assets/arts/80_로고_제목.png": "res://assets/arts/80_로고_제목.png",
	"res://assets/arts/81_로고_제목_행렬.png": "res://assets/arts/81_로고_제목_행렬.png",
	"res://assets/arts/transparent/02_아이콘_마을.png": "res://assets/arts/transparent/02_아이콘_마을.png",
	"res://assets/arts/transparent/03_아이콘_마른강.png": "res://assets/arts/transparent/03_아이콘_마른강.png",
	"res://assets/arts/transparent/04_아이콘_버려진야영지.png": "res://assets/arts/transparent/04_아이콘_버려진야영지.png",
	"res://assets/arts/transparent/05_아이콘_갈라진바닥.png": "res://assets/arts/transparent/05_아이콘_갈라진바닥.png",
	"res://assets/arts/transparent/06_아이콘_오아시스.png": "res://assets/arts/transparent/06_아이콘_오아시스.png",
	"res://assets/arts/transparent/07_아이콘_모래의벽.png": "res://assets/arts/transparent/07_아이콘_모래의벽.png",
	"res://assets/arts/transparent/08_아이콘_뼈의들판.png": "res://assets/arts/transparent/08_아이콘_뼈의들판.png",
	"res://assets/arts/transparent/09_아이콘_독웅덩이.png": "res://assets/arts/transparent/09_아이콘_독웅덩이.png",
	"res://assets/arts/transparent/10_아이콘_무너진담.png": "res://assets/arts/transparent/10_아이콘_무너진담.png",
	"res://assets/arts/transparent/11_아이콘_폭풍의문.png": "res://assets/arts/transparent/11_아이콘_폭풍의문.png",
	"res://assets/arts/transparent/12_아이콘_미지.png": "res://assets/arts/transparent/12_아이콘_미지.png",
	"res://assets/arts/transparent/19_초상_시장.png": "res://assets/arts/transparent/19_초상_시장.png",
	"res://assets/arts/transparent/20_초상_대장.png": "res://assets/arts/transparent/20_초상_대장.png",
	"res://assets/arts/transparent/21_초상_배낭.png": "res://assets/arts/transparent/21_초상_배낭.png",
	"res://assets/arts/transparent/30_아이템_물통.png": "res://assets/arts/transparent/30_아이템_물통.png",
	"res://assets/arts/transparent/31_아이템_식량.png": "res://assets/arts/transparent/31_아이템_식량.png",
	"res://assets/arts/transparent/32_아이템_말린고기.png": "res://assets/arts/transparent/32_아이템_말린고기.png",
	"res://assets/arts/transparent/33_아이템_로프.png": "res://assets/arts/transparent/33_아이템_로프.png",
	"res://assets/arts/transparent/34_아이템_은신막.png": "res://assets/arts/transparent/34_아이템_은신막.png",
	"res://assets/arts/transparent/35_아이템_약초.png": "res://assets/arts/transparent/35_아이템_약초.png",
	"res://assets/arts/transparent/36_아이템_부싯돌.png": "res://assets/arts/transparent/36_아이템_부싯돌.png",
	"res://assets/arts/transparent/37_아이템_정화천.png": "res://assets/arts/transparent/37_아이템_정화천.png",
	"res://assets/arts/transparent/38_배경_열린가방.png": "res://assets/arts/transparent/38_배경_열린가방.png",
	"res://assets/arts/transparent/40_낙서_강.png": "res://assets/arts/transparent/40_낙서_강.png",
	"res://assets/arts/transparent/41_낙서_산.png": "res://assets/arts/transparent/41_낙서_산.png",
	"res://assets/arts/transparent/42_낙서_사구.png": "res://assets/arts/transparent/42_낙서_사구.png",
	"res://assets/arts/transparent/43_낙서_폭풍.png": "res://assets/arts/transparent/43_낙서_폭풍.png",
	"res://assets/arts/transparent/44_낙서_해골.png": "res://assets/arts/transparent/44_낙서_해골.png",
	"res://assets/arts/transparent/45_낙서_경고.png": "res://assets/arts/transparent/45_낙서_경고.png",
	"res://assets/arts/transparent/46_낙서_화살표.png": "res://assets/arts/transparent/46_낙서_화살표.png",
	"res://assets/arts/transparent/58_사람_대원갑.png": "res://assets/arts/transparent/58_사람_대원갑.png",
	"res://assets/arts/transparent/58_사람_대원갑_밝음.png": "res://assets/arts/transparent/58_사람_대원갑_밝음.png",
	"res://assets/arts/transparent/59_사람_대원을.png": "res://assets/arts/transparent/59_사람_대원을.png",
	"res://assets/arts/transparent/59_사람_대원을_밝음.png": "res://assets/arts/transparent/59_사람_대원을_밝음.png",
	"res://assets/arts/transparent/60_사람_대장.png": "res://assets/arts/transparent/60_사람_대장.png",
	"res://assets/arts/transparent/60_사람_대장_밝음.png": "res://assets/arts/transparent/60_사람_대장_밝음.png",
	"res://assets/arts/transparent/61_사람_낙오자.png": "res://assets/arts/transparent/61_사람_낙오자.png",
	"res://assets/arts/transparent/61_사람_낙오자_밝음.png": "res://assets/arts/transparent/61_사람_낙오자_밝음.png",
	"res://assets/arts/transparent/62_사람_스러짐_밝음.png": "res://assets/arts/transparent/62_사람_스러짐_밝음.png",
	"res://assets/arts/transparent/63_기호_흔적점.png": "res://assets/arts/transparent/63_기호_흔적점.png",
	"res://assets/arts/transparent/64_기호_로프다리.png": "res://assets/arts/transparent/64_기호_로프다리.png",
	"res://assets/arts/transparent/65_기호_위치태그.png": "res://assets/arts/transparent/65_기호_위치태그.png",
	"res://assets/arts/transparent/66_기호_넘침배지.png": "res://assets/arts/transparent/66_기호_넘침배지.png",
	"res://assets/arts/transparent/67_기호_주요지점.png": "res://assets/arts/transparent/67_기호_주요지점.png",
	"res://assets/arts/transparent/68_기호_보조지점.png": "res://assets/arts/transparent/68_기호_보조지점.png",
	"res://assets/arts/transparent/69_소품_책갈피리본_우.png": "res://assets/arts/transparent/69_소품_책갈피리본_우.png",
	"res://assets/arts/transparent/69_소품_책갈피리본_좌.png": "res://assets/arts/transparent/69_소품_책갈피리본_좌.png",
	"res://assets/arts/transparent/70_소품_슬롯담김.png": "res://assets/arts/transparent/70_소품_슬롯담김.png",
	"res://assets/arts/transparent/71_소품_슬롯빈.png": "res://assets/arts/transparent/71_소품_슬롯빈.png",
	"‹ 이전": "‹ Back",
	"← 뒤로": "← Back",
	"가": "go",
	"가고 싶은 곳을 누르면\n그 장으로 넘어갑니다.": "Tap where you want to go, and the book turns to that page.",
	"가까이서 보니 물빛이 탁하다.\n손대지 않는 게 낫겠다.": "Up close, the water is murky. Better left untouched.",
	"가리킨 자리를 파 본다": "Dig where it points",
	"가방": "Pack",
	"가방 열기 →": "Open the pack →",
	"가방은 여섯 칸. 담은 만큼이 이번 원정의 목숨이다.": "Six slots in the pack. What you carry is this expedition's life.",
	"가장자리로 비켜 돌아간다": "Skirt around its edge",
	"가장자리에 고인 맑은 물.\n물통을 넉넉히 채운다.": "Clear water pooled at the edge. You fill the waterskins well.",
	"간다": "going",
	"갈 수 있는 곳": "Where you can go",
	"갈라진 바닥": "Cracked Ground",
	"갈라진 바닥에\n마른 갈대 뿌리가 얽혀 있다.\n씹으면 요기는 되지만 물기가 빠진다.": "Dry reed roots tangle through the cracked ground. Chewing them holds hunger off, but wrings you dry.",
	"갈라진 틈 건너기. 다음 원정에도 남음.": "For crossing split ground. Stays for the next expedition.",
	"갈증": "thirst",
	"갈증에 쓰러진 원정들이 노인을 일으켰다.": "The expeditions that collapsed from thirst got the old man on his feet.",
	"갈증을 아는 이": "One who knows thirst",
	"감에 기대어 서둘러 가로지른다": "Trust your gut and hurry across",
	"강": "River",
	"강골": "Hardy one",
	"강골이 마을에 왔다.\n\"주림은 늦출 수 있는 놈이다.\n그거면 하루를 더 걷지.\"": "The hardy one has come to the village. \"Hunger is a thing you can put off. That much buys another day of walking.\"",
	"강바닥 바위에 이전 원정대가\n화살표를 새겼다.\n물길 반대편 마른 둔덕을 가리킨다.\n오가는 데만 한나절 품이다.": "On a riverbed rock, an earlier expedition carved an arrow. It points to a dry mound across the old channel. The trip there and back costs half a day.",
	"강바닥을 따라 파헤친 자국이\n점점이 이어진다.\n이전 원정대가\n물길을 더듬던 손자국이다.": "Dug hollows run along the riverbed, one after another. The marks of the expedition before, hands feeling for the water.",
	"강을 막던 낡은 물막이 담이\n반쯤 무너져 있다.\n돌 틈 아래 고인 물이 어른거린다.": "The old weir that held the river back is half fallen. Water shimmers, pooled beneath the stones.",
	"강행 돌파한다": "Force your way through",
	"같은 그늘에서 잠시 숨을 고른다": "Catch your breath in the same shade",
	"거대한 담이 길을 막았다.\n틈은 좁고 깊다.\n맨몸으로 넘기엔 사나운 벽이다.\n로프를 걸면 다음에도 건널 수 있다.": "A huge wall blocks the way. The gap through is narrow and deep. A savage climb with nothing but your hands. A rope hung here will serve the next crossing too.",
	"거두어 온 이가 다시 주저앉았다.\n이번에는 일으키지 못했다.": "The one you took in sank down again. This time, no one could get them up.",
	"거의 모두가\n길 위에서 죽습니다.\n한 번에 닿은 사람은\n아직 없었습니다.": "Almost all of them\ndie on the road.\nNo one has yet reached the end\nin a single journey.",
	"건너": "cross",
	"건너뛰기": "Skip",
	"건너온 자리다. 이제 주변을 둘러볼 수 있다": "You have crossed over. Now you can look around",
	"건너편에 닿았다.": "Reached the other side.",
	"건너편의 재회": "The reunion on the other side",
	"건드리지 않는다": "Leave them untouched",
	"걸러서 조금만 마신다": "Strain it as best you can and drink a little",
	"걸음마다 닳는 목숨.": "Life, worn away step by step.",
	"검은 바위 그늘에\n물통 여럿이 반쯤 묻혀 있다.\n여기까지 온 원정대가 있었다.": "In the shade of the black rock, waterskins lie half-buried. An expedition once made it this far.",
	"검은 바위가 바람을 가려 주는 자리.\n폭풍에 들기 전 마지막 물이다.\n지금 마셔 힘을 낼지,\n한 모금 아껴 담아 둘지.\n아껴 둔 한 모금은\n폭풍 너머까지 간다.": "A spot where the black rock breaks the wind. The last water before the storm. Drink it now for strength, or set one mouthful aside. A mouthful saved will carry past the storm.",
	"겉에 고인 것만 뜬다": "Scoop only what pools on top",
	"게임을 끝낸다": "Quit the game",
	"곁에서 보폭을 맞춘다": "Walk beside them, matching stride",
	"계속": "Continue",
	"고맙게 건넌다": "Cross with thanks",
	"고맙게 쓰겠다고 되뇐다": "Tell yourself you'll use it well",
	"고맙다": "thanks",
	"고요해진 물낯을 잠시 본다": "Watch the stilled water for a moment",
	"고이 지나친다": "Let it rest and pass by",
	"고인 만큼만 뜨고 간다": "Take only what has pooled and go",
	"고인 물에서 단내가 올라온다.\n갈증엔 유혹이지만 탈이 날지도 모른다.": "A sweetish smell rises from the still water. A temptation to the thirsty, but it may turn the stomach.",
	"고인 물웅덩이를 만났다.\n물빛이 탁하지만, 목은 타들어간다.": "You come upon a pool of standing water. It is murky, but your throat is burning.",
	"곧": "soon",
	"곧 다음 원정대가\n이곳을 향해 온다.\n행렬은 멈추지 않는다.": "Soon the next expedition\nis coming this way.\nThe column does not stop.",
	"곧장 가로지른다": "Cut straight across",
	"곧장 내 길로 간다": "Keep straight on your own path",
	"공간 차단": "Blocked ground",
	"굴러온 덤불": "Tumbled Brush",
	"굴을 파 몸을 숨겨 지난다": "Dig in and pass under cover",
	"굶는 법을 아는 사내가 하나,\n주림에 쓰러졌다는 말이 거듭돼서야\n몸을 일으킨다.": "A man who knows how to starve stirs himself only when talk of people dropping from hunger comes again and again.",
	"굶주려 뒤처진 채,": "Left behind starving,",
	"굶주린": "Starving",
	"굶주림에 한 사람이 뒤처졌다.": "One of them fell behind from hunger.",
	"귀를 막고 눈을 붙인다": "Cover your ears and get some sleep",
	"균열 벽": "Crevice Wall",
	"균열 벽을 타 넘으면 질러갈 수 있다.\n바위가 무르고 미끄럽다.": "Climb the crevice wall and you can cut across. The rock is soft and slick.",
	"균열 턱에 걸린 물통.\n조심히 집어 올린다.": "A waterskin caught on a ledge in the crevice. You lift it out with care.",
	"그 곁에 내 로프를 새로 건다": "Hang a fresh rope beside it",
	"그 자리에서 벌어지는 가장 큰 일. 큰 이중 고리로 눈에 띈다.": "The biggest thing that happens at this place. It stands out as a large double ring.",
	"그가 간 방향으로 마저 걷는다": "Walk on the way they went",
	"그냥 들이켠다": "Gulp it down as it is",
	"그냥 지나친다": "Pass it by",
	"그는 물을 아주 조금씩\n오래 나눠 마신다.\n그러고는 갈라진 목소리로\n한 마디를 꺼낸다.\n\"%s... 우리 이름이었소.\"": "They drink the water in slow, tiny sips, making it last. Then, in a cracked voice, they bring out a single thing to say. \"%s... That was our name.\"",
	"그는 물을 아주 조금씩\n오래 나눠 마신다.\n어느 원정이었는지 물어도\n고개만 젓는다.\n걸음만은 아직 원정대의 것이다.": "They drink the water in slow, tiny sips, making it last. Ask which expedition it was, and they only shake their head. But the stride, at least, is still an expedition's.",
	"그늘 없이 계속 간다": "Keep going without shade",
	"그늘에서 숨을 고른다.\n마른 대추야자 몇 알.": "You catch your breath in the shade. A few dried dates.",
	"그늘을 골라 천천히 되짚는다": "Pick out the shade and work your way back slow",
	"그대로": "unchanged",
	"그들이 선 자리": "Where They Stand",
	"그래도 강행한다": "Push through anyway",
	"그래도 조금 걸러 마신다": "Strain some and drink anyway",
	"그리고": "And",
	"그림": "Art",
	"그림자": "Shadow",
	"그물은 두고 길을 간다": "Leave the net and move on",
	"글꼴": "Fonts",
	"금 간 바닥 틈에\n흙탕물이 조금 고였다.\n걸러서 담는다.": "A little muddy water has pooled in the cracks. You strain it and take it.",
	"기기를 가로로 돌려 주세요": "Please turn your device sideways",
	"기다리지 않고 뚫는다": "Push through without waiting",
	"기리고 계속 간다": "Mourn and go on",
	"기린 자리": "Places mourned",
	"기본 채비": "Standard kit",
	"기어 넘는다": "Clamber over",
	"기운 채로 두고 간다": "Leave it leaning",
	"기울여 잡아 뺀다": "Lean out and pull it loose",
	"기움 자국을 한 번 쓸어 본다": "Run a hand over the stitches",
	"길 위로 모래가\n개울처럼 흘러내린다.\n발목까지 차오르는 모래를\n헤치며 가야 한다.": "Sand pours across the path like a stream. It rises to the ankle, and you must wade through.",
	"길 위의 원정대는 모래에 묻히고,\n세계의 기록만 남는다.": "The expedition on the road will be buried in the sand, and only the world's record will remain.",
	"길 잃은": "Lost",
	"길가 바위에 긁다 만 자국.\n한 글자를 이루지 못한 채\n선 몇 개로 끊겼다.\n폭풍이 먼저 왔는지\n힘이 먼저 다했는지.": "Marks scratched partway into a roadside rock. A few strokes, broken off before they made a letter. Whether the storm came first, or the strength gave out first.",
	"길눈 밝은 떠돌이 하나가\n마을 어귀를 서성인다.\n들판 너머 소식만 기다리는 눈치다.": "A wanderer with a sharp eye for roads lingers at the edge of the village. Waiting, it seems, for word from beyond the fields.",
	"길은 가 본 만큼만 보인다.": "You see only as much of the road as you have walked.",
	"길을 이어 놓은 원정": "An expedition that left the way open",
	"길이 둘로 갈린다.\n메마른 지름길과,\n반나절을 더 도는 먼 길.": "The road forks. A parched shortcut, or a far road that winds half a day longer.",
	"길이 얕은 골로 뚝 끊긴다.\n내려갔다 오를 수는 있어 보인다.\n로프가 있으면 한결 수월하다.": "The path breaks off into a shallow gully. It looks possible to climb down and up again. With a rope it would be far easier.",
	"길잡이": "Pathfinder",
	"깃발": "Banner",
	"깃발을 바로 세워 두고 간다": "Set the banner upright and go",
	"끊긴 선 위에 손가락을 얹어 본다": "Lay a finger on the broken strokes",
	"끝": "end",
	"끝까지 간 원정": "An expedition that went to the end",
	"끝낸다": "Quit",
	"끝에 닿음": "Reached the end",
	"나간다": "Leave",
	"나란한 채로 두고 간다": "Leave them as they are, side by side",
	"나아가는 중...": "On the move...",
	"나침반": "Compass",
	"날 선 바위에 손과 정강이가 쓸렸다.\n상처가 벌겋게 부어오른다.\n천 쪼가리로 덮을 상처가 아니다.": "Sharp rock has scraped hands and shins raw. The wounds swell an angry red. These are not cuts a scrap of cloth will cover.",
	"날린 모래가 해를 가려\n한낮이 저물녘처럼 어둡다.\n길잡이 삼을 것 하나 없는 땅.\n걸음마다 방향을 되짚는다.": "Blown sand veils the sun, and midday is dark as dusk. Nothing in this land to steer by. At every step you check your bearing again.",
	"낡은": "Worn",
	"낡은 궤짝": "Old Chest",
	"남겨둔다 (다음 원정대에게)": "Leave it (for the next expedition)",
	"남겨진": "Left-Behind",
	"남겼다": "Left behind",
	"남기고 계속 간다": "Leave it and go on",
	"남기기": "Leave behind",
	"남긴 물·식량·장막": "Left behind: water · food · tarp",
	"남긴 흔적": "Traces left",
	"남은 것을 챙긴다": "Take what's left",
	"넓힌 물길에 물이 차오르는 것을\n한참 바라본다.\n우리가 다 마실 물이 아니다.\n다음에 올 이들의 물이다.": "You watch a long while as the widened bed fills. This is not water for us to drink. It is for the ones who come next.",
	"눈 감고 뚫고 간다": "Shut your eyes and push through",
	"눈을 가늘게 뜨고 빠르게 벗어난다": "Squint hard and get clear fast",
	"눌린 배낭": "Pinned Pack",
	"느닷없이 모래바람이 몰아친다.\n짧지만 살을 벤다.\n맨몸으로 맞을 바람이 아니다.": "A sand squall tears in from nowhere. Short, but it cuts skin. This is no wind to face in the open.",
	"늦다": "late",
	"늦은": "Late",
	"다 모인 마을": "The village, all gathered",
	"다 살핀 곳": "Searched out",
	"다 함께 떠나 다 함께 닿았다.\n행렬에 빈자리가 없었다.": "They set out together and arrived together. There was no empty place in the column.",
	"다시": "once more",
	"다시 뽑기": "Draw again",
	"다시 한 번, 완벽한 원정을 해낸다면\n무언가 바꿀 수 있지 않을까.": "If we made one more expedition, a perfect one,\nmight something change?",
	"다음": "Next",
	"다음 ›": "Next ›",
	"다음 원정대를 꾸린다": "Gather the next expedition",
	"다친 몸으로 뒤처진 채,": "Left behind hurt,",
	"단내 나는 물": "Sweet-Smelling Water",
	"단단한 가장자리로 돌아간다": "Go around by the firm edge",
	"단단한 바위만 골라 신중히 간다": "Step only on solid rock, slow and sure",
	"닫는다": "Close",
	"달라진 건 없다.": "Nothing has changed.",
	"닳은 문지방을 밟고 넘는다": "Step over the worn threshold",
	"닳은 자리를 한 번 쓸어 본다": "Brush a hand over the worn spot",
	"담 너머": "Beyond the Wall",
	"담 너머는 보이지 않는다.\n넘어봐야 안다.": "There's no seeing past the wall. The only way to know is over.",
	"담 위로 모래가 흘러내려\n틈이 반쯤 메워졌다.\n그래도 지나기엔 좁고 가파르다.\n로프를 걸면 다음에도 건널 수 있다.": "Sand has poured over the wall and half-filled the gap. Still too narrow and steep to pass with ease. A rope hung here will serve the next crossing too.",
	"담 틈에 삭은 로프 한 가닥이\n걸려 있다.\n먼저 온 이가 걸어 둔 것이다.\n몸을 다 맡기기엔 삭았지만\n손잡이 삼을 수는 있겠다.": "A strand of rotted rope hangs in the gap. Someone who came before hung it there. Too far gone to trust with your weight, but it could serve as a handhold.",
	"담은 물건은 다시 눌러서 제거": "Tap an item again to remove it",
	"담을 따라 걷다\n옛 문 자리를 찾았다.\n문짝은 오래전에 삭아 내렸고\n그 자리를 무너진 돌이 메웠다.\n돌을 걷어내는 데 품이 든다.\n로프를 걸면 다음에도 건널 수 있다.": "Walking along the wall, you find where a gate once stood. The doors rotted away long ago, and fallen stone fills the space. Clearing it takes labor. A rope hung here will serve the next crossing too.",
	"당신은 그들을\n거듭 보내는 사람입니다.\n매번 다른 이가 떠나고,\n당신만이 모든 원정을 기억합니다.": "You are the one who sends them,\nagain and again.\nEach time a different person sets out.\nOnly you remember every expedition.",
	"닿은 곳에서는 표시된 지점을\n눌러 살펴봅니다.\n살필 횟수는 정해져 있고,\n살핀다고 물이 줄지는 않습니다.": "Where you arrive, tap the marked spots to look around. The number of searches is fixed, and searching costs no water.",
	"닿은 곳에선 단면이 펼쳐진다.\n표시된 곳을 눌러 살핀다.\n[color=#8a2f1b]살필 횟수[/color]는 정해져 있고,\n살핀다고 물이 줄지는 않는다.": "Where you arrive, the site unfolds. Tap the marked spots to look around. The [color=#8a2f1b]number of searches[/color] is fixed, and searching costs no water.",
	"대오": "Line",
	"더 깊이 판다": "Dig deeper",
	"더미 꼭대기.\n담 너머 협곡 입구가 한눈에 들고,\n돌 틈에 물이 남은 물통 하나가\n손 닿을 거리에 끼어 있다.": "The top of the heap. The canyon mouth beyond the wall lies in full view, and a waterskin with water left in it sits wedged in the stones, within arm's reach.",
	"덮는다": "Close",
	"도구": "Tools",
	"도구 없음": "No tools",
	"도로 묻고 물만 챙긴다": "Bury it again, take only the water",
	"독 웅덩이": "Poison Pool",
	"돌 밑에서 문턱이 드러난다.\n문지방이 발길에 닳아 반질하다.\n담이 성하던 시절\n여기로 오간 사람들의 자국이다.": "Under the stones, the threshold shows itself, worn smooth by footsteps. The mark of all who passed this way when the wall still stood.",
	"돌 처마 밑": "Under the Stone Eaves",
	"돌 표식": "Stone Marker",
	"돌 하나를 더 얹고 간다": "Set one more stone on top and go",
	"돌무더기": "Cairn",
	"돌무더기를 한 번 돌아본다": "Look back once at the stone pile",
	"돌아가": "turn back",
	"돌아간다": "Go back",
	"돌을 걷어내고 문턱을 넘는다": "Clear the stones and cross the threshold",
	"돌을 들어내고 긷는다": "Lift the stones and draw the water",
	"돌탑": "Cairn",
	"돌탑에 하나 더 얹는다": "Set one more stone on the cairn",
	"동트는": "Dawning",
	"되돌릴 수 없다": "This cannot be undone",
	"두 손 모으고 지나친다": "Clasp your hands and pass by",
	"두고 간다": "Leave it behind",
	"두레박": "Pail",
	"둔다": "Leave it",
	"둔다 (짐을 줄인다)": "Leave it (travel light)",
	"둔덕을 타 넘는다": "Climb over the dune",
	"둘러 간다": "Take the long way",
	"둘러볼 것이 없다. 떠난다.": "Nothing to search here. Move on.",
	"둘레를 파 물길을 넓힌다": "Dig the rim wider",
	"뒤": "behind",
	"뒤져 본다": "Search it",
	"뒤처진 이": "Stragglers",
	"든든히 먹고 힘껏 길어 올린다": "Eat your fill and haul with all your strength",
	"들판 너머까지 간 원정이 그를 불렀다.": "An expedition that went beyond the fields called him here.",
	"들판을 훑는 돌풍이 모래를 걷어 올린다.\n묻혀 있던 것들이 드러났다\n다시 묻히기 시작한다.": "A gust sweeps the field and lifts the sand away. Buried things surface, then begin to sink under again.",
	"등불": "Lantern",
	"땡볕에 그물코를 뒤져 거둔다": "Pick through the mesh in the blazing sun",
	"땡볕에 씨름해 꺼낸다": "Wrestle it out under the blazing sun",
	"땡볕에 파내고 뚜껑을 연다": "Dig it out in the sun and open the lid",
	"떠난다": "Set out",
	"떠난다 · 지도로": "Set out · To the map",
	"떠도는": "Wandering",
	"떨며 밤을 버틴다": "Shiver through the night",
	"떼어 챙긴다": "Take it down and pack it",
	"또": "again",
	"또 두 손 모은다": "Clasp your hands once more",
	"라이선스 전문": "Full license text",
	"로프": "Rope",
	"로프 걸 자리를 더듬다가\n반들반들 닳은 돌 턱에 손이 닿는다.\n먼저 온 손들이\n전부 같은 자리를 잡았던 것이다.\n그 위에 우리 매듭을 얹는다.": "Feeling for a place to hang the rope, your hand finds a stone lip worn smooth. Every hand that came before gripped this same spot. You lay your knot over theirs.",
	"로프를 걸고 내려가 걷어 온다": "Fix a rope, go down, and bring it back",
	"로프를 걸어 내려갔다 회수한다": "Rig the rope, then pull it up after",
	"로프를 고정한다": "Fix the rope",
	"마루 부리 © NAVER · Cinzel © Natanael Gama\nSIL 오픈 폰트 라이선스(OFL 1.1)": "MaruBuri © NAVER · Cinzel © Natanael Gama\nSIL Open Font License (OFL 1.1)",
	"마른": "Dry",
	"마른 갈대": "Dry Reeds",
	"마른 강": "Dry River",
	"마른 강바닥에 부서진 수레와\n빈 물통들이 박혀 있다.": "A broken cart and empty waterskins sit lodged in the dry riverbed.",
	"마른 고기와 밧줄이 널려 있다.\n길 위에서도 이렇게 쓸 만한 것들을 찾게 된다.": "Dried meat and rope lie spread out. On the road too, you will find useful things like these.",
	"마을": "Village",
	"마을이 오래 기억할 일이 생겼다.": "The village will remember this for a long time.",
	"마음에 새겨 둔다": "Take it to heart",
	"마지막": "last",
	"마지막 물": "Last Water",
	"막힌 길을 넘기 전엔 떠날 수 없다": "You cannot leave until you cross the blocked way",
	"막힌 자리에 로프를 걸어 두고 갔다.\n이제 어느 원정도\n거기서 멈추지 않는다.": "They rigged a rope where the way was barred, and left it. Now no expedition stops there.",
	"만든 사람": "Made by",
	"만든 이   soomin007": "Made by   soomin007",
	"만든 이들": "Credits",
	"말 없이 기린다": "Mourn without words",
	"말 없이 남긴다": "Leave it without words",
	"말라붙은 강턱에\n고기잡이 그물이 삭아 있다.\n강이 흐르던 시절의 물건이다.\n그물코에 걸린 것들이\n바싹 마른 채 남았다.": "A fishing net lies rotting on the dried bank. A thing from the days when the river ran. What the mesh caught is still there, dried stiff.",
	"말린 고기": "Dried meat",
	"말없이 일어선다": "Stand up without a word",
	"말은 남지 않는다. 물건만 남는다.": "Words do not remain. Only things remain.",
	"맑은 물이 고여 있다.\n떠나면 이런 물 한 모금이 아쉬워진다.": "Clear water pools here. Once you set out, you will miss every mouthful of it.",
	"맞바람에 강행한다": "Push on into the headwind",
	"맞이한다": "Welcome them",
	"매듭만 확인하고 넘는다": "Check the knot and climb over",
	"맨몸으로 무리해서 넘는다": "Force the climb with bare hands",
	"맨손으로 기어 내려갔다 오른다": "Climb down and up bare-handed",
	"맹세": "Oath",
	"먼": "Far",
	"먼 길에서 물이 훨씬 덜 닳는다.\n대신 가볍게 떠나 시작 물이 3 적다.": "Water drains far slower on the long stretches. In return they travel light, starting with 3 less water.",
	"먼 데서 돌아온 이가 마을에 남았다.\n\"길은 물이 마르는 순서대로 외우는 걸세.\"": "One back from far away has stayed in the village. \"You learn a road by the order its waters dry.\"",
	"먼 바깥쪽으로 돌아간다": "Go around, keeping well outside",
	"먼동": "Daybreak",
	"먼저 간 모든 원정대가\n건너편에서 기다리고 있었다.": "Every expedition that went before was waiting on the other side.",
	"먼저 간 모든 원정대가\n기다리고 있었다.\n행렬이 멈춘다.\n드디어 그쪽에서 만난다.": "All the expeditions that went before\nwere waiting.\nThe column stops.\nAt last, we meet on the other side.",
	"먼저 간 원정대": "The expeditions that went before",
	"먼저 떠난 이들의 자리다.\n돌아온 원정대는 아직 없다.": "This is the place of those who left before. No expedition has come back yet.",
	"먼지 쓴": "Dust-Covered",
	"멀다": "far",
	"멀리 가 본 이": "One who has been far",
	"멀리 돌아 우회한다": "Swing wide around",
	"멀리 물빛이 어른거린다.\n아지랑이인지 진짜인지 알 수 없다.": "Far off, a glimmer of water. Heat haze or the real thing, there is no telling.",
	"멈추려면 그를 밀어내야 했다.\n이제 이 자리에 선 것은\n우리다.": "To stop it, we had to push them out.\nNow the ones standing in this place\nare us.",
	"멈춰 선다.": "The column halts.",
	"멈춰서 게워내고 간다": "Stop, retch, and move on",
	"메마른": "Parched",
	"메아리": "Echo",
	"모닥불": "Campfire",
	"모든 길을 밟은 원정대들": "Expeditions that walked every road",
	"모래": "Sand",
	"모래 더미를 밟고 무리해서 넘는다": "Force a way over the piled sand",
	"모래 둔덕 사이 작은 샘.\n드물게도 맑은 물이 고여 빛나고,\n야자 그늘엔 떨어진 열매가 몇.": "A small spring between the dunes. Clear water, a rare thing, pools and glints, and a few fallen fruits lie in the palm shade.",
	"모래 둔덕에 걸린 천 자락.\n앞선 원정대가 두고 간 물통과\n마른 열매가 싸여 있었다.": "A strip of cloth snagged on a dune. Inside it, a waterskin and dried fruit left by an earlier expedition.",
	"모래 둔덕에 천막 한 귀퉁이가\n삐져나와 있다. 파내면 장막이 될지도.\n파는 동안 바람에 시달린다.": "The corner of a tent pokes out of a dune. Dug free, it might serve as a tarp. The wind will batter you while you dig.",
	"모래 벽에도\n바람이 눕는 때가 있다.\n해거름의 짧은 틈.\n그때까지 웅크린 기다림은\n먹을 것을 축낸다.": "Even the wall of sand has times when the wind lies down. A short gap at dusk. Waiting for it, hunkered low, eats into the food.",
	"모래 위에 돌을 세워 만든 표식.\n곁에 긁어 새긴 자국: [ 앞 · 없다 ]": "A marker of stones set upright on the sand.\nScratched beside it: [ ahead · nothing ]",
	"모래가 다시 가라앉았다.": "The sand has settled again.",
	"모래가 얕은 등성이로 돌아간다": "Go around by the ridge where the sand runs shallow",
	"모래를 털고 바로 놓아 준다": "Brush off the sand and set them upright",
	"모래바람 속": "In the Sandstorm",
	"모래에 반쯤 묻힌 빈 물통.\n바닥에 서툰 글씨가 긁혀 있다:\n[ 여기 · 끝 ]": "An empty waterskin, half-buried in the sand. Clumsy letters are scratched into the base:\n[ here · end ]",
	"모래에 반쯤 묻힌 뼈들.\n두 손을 모으고 지나친다.": "Bones half-buried in the sand. You clasp your hands and pass by.",
	"모래에 반쯤 묻힌 솥이 엎어져 있다.\n안에 마른 곡물이 눌어붙었다.": "A pot lies overturned, half-buried in sand. Dried grain has crusted to the inside.",
	"모래에 반쯤 묻힌 자루.\n아직 상하지 않았다.": "Sacks half-buried in the sand. Not spoiled yet.",
	"모래에 반쯤 지워진 발자국.\n이전 원정대도\n여기까지는 왔던 모양이다.\n자국은 내 길에서 벗어나\n한쪽으로 휘어 사라진다.": "Footprints half-erased in the sand. The expedition before made it this far, it seems. The tracks leave your path, curving off to one side until they vanish.",
	"모래의 벽": "Wall of Sand",
	"모래폭풍은 글을 지웁니다.\n말은 남지 않고,\n물건만 남습니다.": "The sandstorm erases writing.\nWords do not remain.\nOnly things remain.",
	"모래폭풍이 모든 원정과 흔적을 쓸어 간다.\n처음부터 다시 시작한다.\n원정 %d번 · 흔적 %d개가 사라진다.": "The sandstorm sweeps away every expedition and every trace. Everything starts over from the beginning. %d expeditions · %d traces will be lost.",
	"목마른": "Thirsty",
	"목마른 채 계속 간다": "Walk on thirsty",
	"목마름에 한 사람이 쓰러졌다.": "One of them collapsed from thirst.",
	"목적지에 닿았다.": "You have reached the end.",
	"목적지에 닿았다.\n죽지 않고, 온전히.": "We reached the destination.\nAlive, and whole.",
	"몸을 낮추고 견딘다": "Get low and endure it",
	"몸을 낮추고 버틴다": "Keep low and endure",
	"몸이 불덩이 같다.\n열이 오르고 다리가 풀린다.\n약 없이 버틸 열이 아니다.": "Your body burns like a coal. The fever climbs and your legs give out. This is not a fever to sit out without medicine.",
	"못": "can't",
	"못 지나가 그 자리서 소진": "No way past, spent on the spot",
	"못다 새긴 말을 짐작하며 간다": "Guess at the unfinished word and go",
	"무겁게 진 출발을 보고 짐을 자청했다.": "He saw a heavy-laden departure and volunteered his back.",
	"무겁게 짐을 진 행렬 얘기만 나오면\n어깨부터 푸는 젊은이가 있다.": "There is a young man who starts loosening his shoulders at any talk of a heavy-laden column.",
	"무너져 내린 돌이 처마처럼 얹혔다.\n그늘 밑 모래가 축축하다.\n꾹 눌러 파니\n물이 한 모금만큼 고인다.": "Fallen stone sits overhead like eaves. The sand in its shade is damp. You press and dig, and a mouthful of water pools.",
	"무너지기 전에 내달린다": "Run before it comes down",
	"무너진 담": "Fallen Wall",
	"무너진 담을 기어오르면 넘을 수 있다.\n돌이 무르다.": "You could clamber up the fallen wall and over. The stone is crumbly.",
	"무너진 비탈에서 발을 헛디뎠다.\n발목이 시큰거린다.\n절뚝이는 걸음엔\n땡볕 길이 갑절이다.": "A foot slips on a crumbled slope. The ankle throbs. On a limping stride, a sun-baked road counts double.",
	"무너진 천막": "Collapsed Tent",
	"무너진 천막 골조에\n성한 장막 한 장이 걸려 있다.\n떼어 가면 폭풍에 든든하지만\n짐이 된다.": "One sound tarp still hangs on the collapsed tent frame. Taken along, it would stand you well in a storm, but it is weight to carry.",
	"무너진 틈에 배낭이 끼어 있다.\n물통과 식량이 남았다.": "A pack sits wedged in the fallen gap. Waterskins and food remain.",
	"무른 돌더미": "Crumbling Rubble",
	"무엇을 남길까": "What to leave behind",
	"묵념하고 지나친다": "Bow your head and pass by",
	"문 아래": "Under the Gate",
	"문으로 드는 길가에 돌무더기.\n여기까지 온 원정대들이\n하나씩 얹고 갔다.\n곁에 긁힌 표식: [ 마지막 · 또 ]": "A cairn by the path into the gate. Every expedition that made it this far added one stone. Scratched beside it: [ last · again ]",
	"물": "Water",
	"물 %d": "Water %d",
	"물 %d · 식량 %d · %s · 무게 %d%s": "Water %d · Food %d · %s · Weight %d%s",
	"물 6, 식량 5를 더 지고 시작한다.\n대신 짐이 무거워\n먼 길에서 물이 더 빨리 닳는다.": "Starts with 6 more water and 5 more food. In return the load is heavy, and water drains faster on the long stretches.",
	"물가": "Water's Edge",
	"물가 발자국": "Waterside Tracks",
	"물가 진흙": "Mudflat",
	"물가 진흙을 파\n웅덩이를 넓혀 둔다.\n지금 손에 쥐는 물은 없지만,\n다음에 올 이들 몫이 깊어진다.": "You dig out the waterside mud and widen the pool. Nothing in hand for it now, but the share of those who come next runs deeper.",
	"물건 셋을 길에 남기는 것을 보고 왔다.": "Having seen three things left on the road, they came.",
	"물건 하나를 여기 둔다. 그만큼 잃지만, 계속 갈 수 있다.": "You set one thing down here. You lose that much, but you can go on.",
	"물건을 남길 때 잃는 것이 1 적다.\n(물 4 → 3, 식량 3 → 2)\n대신 짐을 아껴 시작 물이 2 적다.": "Leaving a thing behind costs 1 less. (Water 4 → 3, food 3 → 2.) In return they carry less, starting with 2 less water.",
	"물건을 누르면 설명이 나온다.": "Tap an item to see what it is.",
	"물길": "Waterway",
	"물길을 읽는 노인은\n갈증에 쓰러진 원정 소식을\n못 본 체하지 못한다.": "The old man who reads watercourses cannot look away when word comes of expeditions collapsing from thirst.",
	"물길인 줄 알았던 자리가\n바싹 말라 갈라졌다.\n틈 아래엔 아직 물기가 비치고,\n앞은 한참 마른 구간이다.": "What looked like a watercourse lies dried and cracked. Down in the cracks a dampness still shows, and ahead is a long dry stretch.",
	"물만 나눠 담고 틈에 도로 둔다": "Share out the water and leave the skin in the gap",
	"물만 옮겨 담고 물통은 도로 끼운다": "Take only the water and wedge the skin back",
	"물빛이 있던 자리엔\n소금기만 허옇게 낀 바닥뿐이다.\n어느새 길에서 꽤 벗어났다.": "Where the water shone there is only a floor crusted white with salt. Somewhere along the way you strayed far off the path.",
	"물을 나눠 주고 행렬에 거둔다": "Share your water and take them into the column",
	"물을 뜨고 돌 하나를 더 얹는다": "Draw water and add one more stone",
	"물을 뜨고 열매도 거둔다": "Draw water and take the fruit as well",
	"물을 뜨고 열매도 줍는다": "Draw water and gather fruit too",
	"물을 뜨자 물낯이 흔들리고\n비친 얼굴이 잠시 흩어진다.\n이 샘은 지금껏 몇 사람의 얼굴을\n비추고, 지웠을까.\n물낯은 곧 다시 고요해진다.": "As you draw water, the surface trembles and the reflected face scatters for a moment. How many faces has this spring held and erased? Soon the water is still again.",
	"물을 아끼지 않고 강행한다": "Push on without sparing the water",
	"물을 얻을 때마다 1을 더 얻는다.\n대신 먼 길에서 물이 더 빨리 닳는다.": "Gains 1 extra whenever water is found. In return, water drains faster on the long stretches.",
	"물이 끊겨 뒤처진 채,": "Left behind when the water gave out,",
	"물이 떨어졌다. 여기서 갈증으로 끝났다.": "The water runs out. It ends here, in thirst.",
	"물이나 식량, 흔적, 작은 일이 있을 수 있다.": "There may be water, food, a trace, or some small happening.",
	"물지기": "Waterkeeper",
	"물지기가 마을에 왔다.\n\"어느 바닥에 물이 숨었는지\n늙은이는 냄새로 아네.\"": "The waterkeeper has come to the village. \"Which ground hides water, an old man knows by the smell.\"",
	"물통": "Waterskin",
	"물통만 거두고 간다": "Take only the waterskins and go",
	"물통만 채우고 간다": "Fill only the waterskins and go",
	"물통을 가득 채운다": "Fill the waterskins to the brim",
	"물통을 거둔다": "Gather the waterskins",
	"물통을 꺼내 들고 내려선다": "Pull the waterskin out and climb down",
	"물통을 넉넉히 채운다": "Fill the waterskins well",
	"물통을 뒤진다": "Go through the waterskins",
	"물통을 메고 돌아선다": "Shoulder the waterskins and turn away",
	"물통을 채운다": "Fill the waterskins",
	"물통을 풀어 챙긴다": "Untie the waterskins and take them",
	"물통을 풀어내자 깃대가 기운다.\n바람에 깃발이 크게 한 번 운다.\n이 깃발을 보고 여기까지 온\n원정대도 있었을 것이다.": "As the waterskins come loose, the flagpole tilts. The banner cries out once, loud, in the wind. Some expeditions surely made it this far because they saw this banner.",
	"물통째 챙겨 마저 오른다": "Take the whole skin and finish the climb",
	"미련 없이 지나친다": "Pass it by without regret",
	"미안": "sorry",
	"밀어내지 않아도 되었다.\n지나쳐, 건너편으로.": "We did not have to push anyone out.\nWe pass through, to the other side.",
	"바닥까지 긁어 담는다": "Scrape it out to the bottom",
	"바닥을 판다": "Dig into the bed",
	"바닥이 보이지 않는다.\n손을 넣을 엄두가 안 난다.": "There is no seeing the bottom. You dare not reach a hand in.",
	"바람": "Wind",
	"바람 그늘": "Wind Shadow",
	"바람 그늘에 몸을 묻을\n모래 굴을 팔 수 있다.\n물을 쓰지만 폭풍을 덜 맞고 지난다.": "In the wind's shadow, you could dig a burrow to shelter in. It costs water, but the storm will touch you less.",
	"바람 맞으며 헤집어 꺼낸다": "Brave the wind and pick it free",
	"바람 탄": "Windborne",
	"바람에 걸린 천": "Wind-Caught Cloth",
	"바람에 굴러온 마른 덤불 뭉치.\n누군가 싼 마른 열매 꾸러미가\n덤불에 걸려 있다.\n바람을 맞아 가며 헤집어야 한다.": "A knot of dry brush blown in on the wind. A wrapped bundle of dried fruit hangs snagged in it. You'll have to pick it apart with the wind in your face.",
	"바람에 모래가 섞이기 시작한다.\n숨을 쉴 때마다\n이 사이에 모래가 씹힌다.": "Sand starts to ride the wind. Every breath leaves grit grinding between your teeth.",
	"바람을 피한 그늘에\n사람이 웅크리고 있다.\n'%s' 원정의 사람이다.\n%s\n여기까지 버티고 있었다.": "Someone crouches in a hollow, out of the wind. They walked with '%s'. %s they have held on this far.",
	"바람을 피한 그늘에\n사람이 웅크리고 있다.\n지난 원정에서 뒤처진 이가,\n여기까지 버티고 있었다.": "Someone crouches in a hollow, out of the wind. One left behind by a past expedition, and they have held on this far.",
	"바람의 결을 읽으며 천천히 간다": "Read the grain of the wind and go slow",
	"바람이 앞을 삼킨다.\n발을 들일 엄두가 안 난다.": "The wind swallows the way ahead. You dare not set foot in it.",
	"바위 그늘에 나무 그릇 두 개가\n나란히 엎어져 있다.\n모래가 반쯤 삼켰어도\n나란한 것은 그대로다.\n곁의 표식: [ 고맙다 ]": "In the shade of a rock, two wooden bowls lie overturned side by side. The sand has half swallowed them, but side by side they remain.\nA marker beside them: [ thanks ]",
	"바위 턱이 실낱처럼 좁아진다.\n한쪽은 벽, 한쪽은 낭떠러지.": "The rock ledge narrows to a thread. Wall on one side, a sheer drop on the other.",
	"발이 푹푹 빠지는 고운 모래밭.\n한 걸음이 두 걸음 같다.": "Fine sand that swallows every step. One stride feels like two.",
	"발자국": "Footprint",
	"발자국은 낮은 바위 그늘에서 끊긴다.\n먼저 간 이가 쉬어 간 자리다.\n재도 뼈도 없다.\n다시 일어나 걸었다는 뜻이다.": "The footprints end in the shade of a low rock. Someone who went before rested here. No ash, no bones. It means they got up and walked on.",
	"밟은 길": "Trodden path",
	"밤길": "Night Road",
	"배경음악": "Music",
	"배낭 챙기기 →": "Pack the bag →",
	"배낭을 챙긴다": "Pack the bag",
	"뱉고 간다": "Spit them out and go",
	"버려진 야영지": "Abandoned Camp",
	"버려진 장막을 챙긴다": "Take the abandoned tarp",
	"베타 %s  ·  만든 이들": "Beta %s  ·  Credits",
	"벼랑 끝": "Cliff's Edge",
	"벽 중턱, 바람이 판 홈마다\n먼저 오른 이들의 손자국이 남았다.\n홈 하나에 물이 반쯤 남은\n가죽 물통이 끼워져 있다.": "Halfway up the wall, every wind-carved hollow holds the hand-marks of earlier climbers. In one hollow, a leather waterskin sits wedged, half full.",
	"벽돌 사이에 천으로 싼 꾸러미.\n마른 먹을거리 냄새가 난다.\n틈이 좁아 긁히지 않고는\n못 꺼내겠다.": "A cloth-wrapped bundle between the bricks. It smells of dried food. The gap is too tight to get it out without scraping skin.",
	"벽돌 틈": "Between the Bricks",
	"벽에 붙어 조심조심 건넌다": "Press against the wall and edge across",
	"별": "Star",
	"보낸 원정": "Expeditions sent",
	"보낸 원정 %d  ·  남긴 흔적 %d": "Expeditions sent %d  ·  Traces left %d",
	"봇짐을 거두어 간다": "Take the bundle along",
	"봐": "see",
	"부러진 깃대에\n원정대 깃발이 걸려 나부낀다.\n깃대 밑에 가죽 물통 몇이 묶여 있다.": "An expedition banner flutters from a broken flagpole. A few leather waterskins are tied at its base.",
	"부서진": "Broken",
	"부서진 수레": "Broken Cart",
	"부서진 수레가 모래에 처박혀 있다.\n짐칸에 먹을 것이 남은 눈치다.\n그늘 한 점 없는 땡볕 아래서다.": "A broken cart lies rammed into the sand. Something to eat is left in the bed, by the look of it. It sits under a blazing sun, without a scrap of shade.",
	"부싯돌": "Flint",
	"부싯돌로 불을 피운다": "Strike a fire with the flint",
	"불은 오래전에 꺼졌다.\n쓸 것이 없다.": "The fire died long ago. Nothing left to use.",
	"붉은": "Red",
	"비었다": "Empty",
	"빈 물통을 챙겨 둔다": "Take the empty waterskin along",
	"빛바랜": "Faded",
	"뼈": "Bone",
	"뼈 무더기": "Heap of Bones",
	"뼈 무더기 아래\n가죽 배낭이 눌려 있다.\n마른 먹을거리가 남은 눈치다.\n들어내는 데만 땡볕에 한참이다.": "A leather pack lies pinned beneath the heaped bones. By the look of it, dried food remains inside. Working it free means a long stretch in the blazing sun.",
	"뼈 무더기 위에 누군가\n돌을 쌓아 표식을 남겼다.\n글씨는 모래에 지워졌다.": "Over the heaped bones, someone piled stones for a marker. The sand has erased the writing.",
	"뼈 사이 돌 표식에\n돌 하나를 얹어 애도한다.\n이름 모를 원정대에게.": "You set one more stone on the marker among the bones, in mourning. For an expedition no one can name.",
	"뼈 사이에 굴러다니는 물통들.\n아직 몇 모금 남았다.": "Waterskins rolling loose among the bones. A few mouthfuls still in them.",
	"뼈의 들판": "Field of Bones",
	"사체를 끌어내 모래에 묻는다": "Haul the carcass out and bury it",
	"사체를 끌어낸 자리에\n모래를 덮고 돌을 얹는다.\n물이 맑아지는 것을\n우리는 보지 못하고 떠난다.\n그래도 손은 개운하다.": "Sand goes over the spot where it lay, and stones on top. The water will clear after we are gone. Still, the hands feel clean.",
	"삭은 줄을 걷어 내리는데\n매듭이 낯익다.\n우리가 쓰는 매듭법 그대로다.\n같은 마을에서 배워 온 손이\n먼저 여기 닿았던 것이다.": "Taking down the rotted rope, you know the knot at a glance. It is the very knot we tie. Hands taught in the same village reached here first.",
	"삭은 줄을 손잡이 삼아 넘는다": "Cross using the rotted rope as a handhold",
	"삭은 줄이라 둔다": "The rope's rotted, leave it",
	"살펴본다": "Take a look",
	"살핀다": "Look around",
	"살필 곳": "A spot to search",
	"상황": "Situation",
	"새 매듭을 당겨 보고 넘는다": "Test the new knot and cross",
	"새겨진 대로 마음에 새기고 간다": "Take it to heart, as it is written, and go",
	"새긴 화살표": "Carved Arrow",
	"새벽": "Dawn",
	"샘": "Spring",
	"샘가에 바람이 자고,\n물낯이 거울처럼 고요하다.\n물가엔 야자 열매도 떨어져 있다.": "The wind sleeps at the spring, and the water's face is still as a mirror. Fallen palm fruit lies at the water's edge.",
	"샘이 얕다.\n둘레를 파 물길을 넓히면 더 고이겠지만,\n파는 데 기운이 든다.": "The spring is shallow. Dig the rim wider and more would gather, but the digging takes strength.",
	"서둘러 길을 되짚는다": "Hurry back the way you came",
	"설정": "Settings",
	"세 번 남긴 이": "One who left three behind",
	"세계의 기록은 남는다.\n다음에 이어서 원정을 보낼 수 있다.": "The world's record remains. You can carry on sending expeditions next time.",
	"세이브 열기 실패: %s": "Failed to open save: %s",
	"세이브 파싱 실패 — 무시": "Failed to parse save; ignoring",
	"소리": "Sound",
	"소리 켜기": "Turn sound on",
	"소모": "Attrition",
	"속이 뒤집힌다.\n아까 그 물이 탈이 났다.\n폭풍 앞에서 다리가 풀린다.": "Your stomach turns. That water from earlier has done its work. Facing the storm, your legs go weak.",
	"속지 않고 길을 지킨다": "Ignore it and keep to the path",
	"손을 털고 길을 간다": "Dust off your hands and walk on",
	"손이 안 닿는 것은 둔다": "Leave what the hand can't reach",
	"솥째 두고 간다": "Leave it, pot and all",
	"수레는 오래전에 부서졌다.\n쓸 만한 건 이미 누가 가져갔다.": "The cart broke long ago. Whatever was worth taking is already gone.",
	"숨죽여 빠르게 지난다": "Hold your breath and slip through fast",
	"숨죽인": "Hushed",
	"쉬지 않고 가로지른다": "Cross without resting",
	"시간 압박": "Time pressure",
	"시작": "Begin",
	"시장: 가다가 닿는 곳마다\n[color=#D6B278]두 군데[/color] 정도는 살펴볼 여유가 있을 걸세.\n그 시간 동안은 자유롭게 둘러보게.": "Trader: At each place you reach along the way, you'll have time enough to look around [color=#D6B278]two spots[/color] or so. Spend that time as you please.",
	"시장: 가방은 [color=#D6B278]여섯 칸[/color]뿐일세.\n[color=#D6B278]물[/color]하고 [color=#D6B278]먹을 것[/color]부터 챙기게. 그게 목숨이야.\n폭풍용 [color=#D6B278]장막[/color]과 [color=#D6B278]로프[/color]도\n분명 쓸 일이 있을 것이네.": "Trader: The pack is [color=#D6B278]six slots[/color], no more. [color=#D6B278]Water[/color] and [color=#D6B278]something to eat[/color] come first. That's your life right there. A storm [color=#D6B278]tarp[/color] and a [color=#D6B278]rope[/color] will find their use too, sure enough.",
	"시장: 끝에 닿았다 왔다지.\n그런데도 원정은 끝나질 않는군.": "Trader: You reached the end and came back, so they say. And yet the expeditions don't end.",
	"시장: 또 떠나는군. 부디 조심히 가게.": "Trader: Off again, then. Walk careful out there.",
	"시장: 무엇을 지고, 누가 이끌지 정하게.\n물과 식량이 곧 목숨일세.": "Trader: Decide what you'll carry and who will lead. Water and food are your life out there.",
	"시장: 아, 그리고 원정이 끝나기 전에\n[color=#D6B278]딱 한 번, 물건 하나[/color]를 길에 남길 수 있네.\n자네가 끝내 닿지 못할 때를 대비해\n다음 원정대에게 전하는 걸세.\n무엇을 어디에 언제 둘지 잘 생각해 보게.": "Trader: Ah, and before the expedition ends, you can leave [color=#D6B278]one thing, just once[/color], on the road. It's for passing on to the next expedition, in case you never reach the end yourself. Think well on what to set down, and where, and when.",
	"시장: 어디로 향할지는\n자네에게 달려 있네.\n먼 곳일수록 시간도 오래 걸리고,\n그만큼 [color=#D6B278]물[/color]과 [color=#D6B278]식량[/color]도 많이 필요하겠지.": "Trader: Where you head is up to you. The farther the place, the longer the road, and the more [color=#D6B278]water[/color] and [color=#D6B278]food[/color] you'll be needing.",
	"시장: 옛말이 하나 있긴 하지.\n잠든 이들을 [color=#D6B278]기리고[/color], 뒤처진 이들을 [color=#D6B278]거두고[/color],\n[color=#D6B278]한 사람도 잃지 않고[/color] 닿은 원정만이\n밀어내지 않고 지나간다고.": "Trader: There's an old saying, mind you. Only an expedition that [color=#D6B278]mourns[/color] the ones sleeping, [color=#D6B278]takes in[/color] the ones left behind, and arrives [color=#D6B278]without losing a single soul[/color] passes through without pushing anyone out.",
	"시장: 왠지 자네도 알 것 같네만.\n죽은 자리를 지나치지 말고,\n길에 웅크린 이가 보이거든 거두게.\n옛말이 다 헛말은 아닐 걸세.": "Trader: Something tells me you know it already. Don't pass by where they fell, and if you see someone huddled on the road, take them in. The old sayings aren't all empty talk.",
	"시장: 이 기록지를 가져가게.\n떠난 이들의 이야기가 여기 적힐 걸세.\n화면 귀퉁이 [color=#D6B278]책갈피[/color]를 누르면 언제든 볼 수 있네.": "Trader: Take this journal. The stories of those who set out will be written in it. Press the [color=#D6B278]bookmark[/color] in the corner of the screen and you can read it any time.",
	"시장: 잘 왔네. 채비를 도와줌세.": "Trader: There you are. Let me help you get ready.",
	"시장: 짐을 챙길 때는\n필요한 만큼만 챙기게.\n무거운 짐은 [color=#D6B278]물[/color]을 더 마시게 하거든.\n어깨가 가벼워야 오래 걷는 법이지.": "Trader: When you pack, take only what you need. A heavy load makes you drink more [color=#D6B278]water[/color]. Light shoulders walk far, that's the way of it.",
	"시체": "Body",
	"식량": "Food",
	"식량 %d": "Food %d",
	"식량 자루": "Food sack",
	"식량 자루를 챙긴다": "Take the food sacks",
	"식량이 떨어졌다. 더 가지 못했다.": "The food runs out. They can go no further.",
	"식량이 절반 속도로 닳는다.\n(두 걸음마다 1 → 네 걸음마다 1)\n대신 먼 길에서 물이 조금 더 빨리 닳는다.": "Food wears down at half speed. (1 every two steps → 1 every four steps.) In return, water drains a little faster on the long stretches.",
	"식은 모닥불 자리.\n서둘러 떠났는지 먹다 만 것들이\n재 옆에 그대로 흩어져 있다.": "A cold fire pit. They must have left in a hurry; half-eaten food lies scattered beside the ashes.",
	"식은 재": "Cold Ashes",
	"신발을 가지런히 놓아 둔다": "Set the shoe down neatly",
	"씹어 넘긴다": "Chew and swallow",
	"아까 그 물이 속에서 뒤척인다.\n식은땀이 난다.\n멈춰 게워낼지 참고 갈지.": "That water from before turns in your gut. A cold sweat breaks. Stop and retch, or hold it down and walk.",
	"아니, 머문다": "No, stay",
	"아래": "down",
	"아무 키나 눌러 계속": "Press any key to continue",
	"아무것도 남기지 않고 간다": "Go on without leaving anything",
	"아무것도 없다.": "There is nothing.",
	"아무도 잃지 않은 원정": "An expedition that lost no one",
	"아이들": "Children",
	"아직": "not yet",
	"아직 떠난 원정이 없다.": "No expedition has set out yet.",
	"아직 적을 것이 없다.\n길이 하나씩 가르쳐 줄 것이다.": "Nothing to write yet. The road will teach you, one thing at a time.",
	"안전": "safe",
	"안전하게 돌아간다": "Turn back and go the safe way",
	"앞": "ahead",
	"앞서 채운 물이 아직 넉넉하다.\n폭풍 앞에서도 조금은 든든하다.": "The water drawn earlier still holds plenty. Even facing the storm, it is some comfort.",
	"앞선 이의 유품": "Keepsakes of Those Before",
	"앞이 바싹 메말랐다.\n한참 물 한 방울 없을 듯하다.\n지름길엔 그늘 한 점 없고,\n돌아가는 길은 한나절이 멀다.": "The land ahead is bone-dry. Not a drop of water for a long way, by the look of it. The shortcut has no shade at all, and the way around costs half a day.",
	"앞이 온통 모래바람이다.\n폭풍 구간이 길게 이어진다.\n장막 없이 뚫기엔 너무 긴 벽이다.": "Ahead is nothing but driving sand. The storm stretch runs long. Too long a wall to break through without a tarp.",
	"야영지 우물": "Camp Well",
	"야영지에서 챙긴 여분 장막이 있다.\n이번 폭풍은 한결 든든하게 버틴다.": "You have the spare tarp taken from the camp. This storm will be far easier to sit out.",
	"야자 그늘": "Palm Shade",
	"야자 꼭대기": "Top of the Palm",
	"야자 꼭대기에 열매가 매달려 있다.\n오르면 딸 수 있지만 기운이 빠진다.": "Fruit hangs at the palm's crown. You could climb for it, but the climb will drain you.",
	"약속": "Promise",
	"약초": "Herbs",
	"약초 꾸러미": "Herb bundle",
	"약초로 상처를 싸맨다": "Dress the wounds with herbs",
	"약초로 싸매고 간다": "Bind it with herbs and go",
	"약초로 열을 다스린다": "Bring the fever down with herbs",
	"어떤 말을 새길까": "What words to engrave",
	"언 밤의 불": "Fire on frozen nights",
	"언 밤의 불 피우기.": "For a fire on a frozen night.",
	"언제든 [남기기]로 물건 하나를\n두고 갈 수 있습니다.\n그만큼 잃지만, 다음 원정대가\n그것을 줍습니다.": "You can tap [Leave something] at any time to put one thing down. You lose that much, but the next expedition picks it up.",
	"없다": "nothing",
	"엔진": "Engine",
	"여기": "here",
	"여기 잠든 이를 기린다 · 표식만 남긴다": "Mourn the one sleeping here · leave only a marker",
	"여기 잠든 이를 기린다. 돌 위의 말은 다음 원정대도 읽는다.": "You mourn the one sleeping here. The next expedition, too, will read the words on the stone.",
	"여기까지.  아무 키나 누르면 돌아간다.": "That is all.  Press any key to return.",
	"여기는 마을일세. 길을 나서면\n닿는 곳마다 몇 군데 둘러보게 되지.\n둘러볼 횟수는 정해져 있으니 잘 고르게.\n여기선 아무 일도 없으니 편히 연습해 보게.": "This here is the village. Out on the road, every place you reach has a few spots worth looking over. You only get so many looks, so choose them well. Nothing happens here, so practice all you like.",
	"여기서 끝났다.": "It ends here.",
	"여기서 덮을까": "Close the book here?",
	"여분 장막을 친다": "Pitch the spare tarp",
	"여정": "Journey",
	"연출": "Motion",
	"열·탈진 다스리기.": "For treating fever and exhaustion.",
	"열·탈진 다스림": "Eases fever and exhaustion",
	"옛 줄을 고이 걷어 둔다": "Coil the old rope down with care",
	"오래 보지 않고 장막을 갠다": "Fold the tarp without looking long",
	"오래가는 식량. 대신 짜서 더 마른 목.": "Food that keeps. Salty, though, and the throat runs drier.",
	"오아시스": "Oasis",
	"오프닝 다시보기": "Replay the opening",
	"올 사람은 다 왔다.\n원정이 겪은 일들이\n사람을 하나씩 마을에 앉혔다.": "Everyone who was going to come has come. What the expeditions lived through seated them in the village, one by one.",
	"올라가 딴다": "Climb up and pick it",
	"우물": "Well",
	"우물 바닥에 물이 조금 남았다.\n두레박 줄이 삭아\n길어 올리기 수고롭다.": "A little water remains at the bottom of the well. The bucket rope has rotted through; hauling it up is hard going.",
	"웅덩이 가장자리 마른 갈대.\n뿌리를 씹으면 요기는 된다.": "Dry reeds at the pool's edge. Chewing the roots holds hunger off a little.",
	"웅덩이 가장자리에 발자국이 어지럽다.\n여럿이 여기서 물을 마셨고,\n그중 몇은 되돌아가지 않았다.\n두고 간 봇짐 하나가 눈에 띈다.": "Footprints crowd the pool's edge. Many drank here, and some of them never went back. A bundle someone left behind catches the eye.",
	"웅덩이 옆에 짐승 사체가 삭고 있다.\n물맛이 왜 그런지 알 것 같다.\n끌어내 묻자면 한나절 품이다.": "An animal carcass rots beside the pool. That would explain the taste. Hauling it out and burying it would take half a day.",
	"웅덩이에 등을 돌린다": "Turn your back on the pool",
	"웅덩이에 새 한 마리가 죽어 떠 있다.\n물을 마신 대가일까.\n그래도 목은 탄다.": "A bird floats dead on the pool. The price of drinking here, maybe. Still, the throat burns.",
	"웅크려 바람을 보낸다": "Crouch down and let the wind pass",
	"웅크린 사람": "A crouched figure",
	"원정 %d · 흔적 %d · 죽음 %d": "Expeditions %d · Traces %d · Deaths %d",
	"원정 이야기는 마을에 금방 퍼진다.\n소문을 듣고, 하나둘 찾아온다.": "Word of the expeditions spreads quickly through the village. One by one, people hear it and come.",
	"원정 이어가기": "Continue the expedition",
	"원정 일대기": "Chronicle of Expeditions",
	"원정 하나가 끝까지 걸었다.\n돌아오지는 못했다.": "One expedition walked all the way to the end. It did not come back.",
	"원정대": "The expedition",
	"원정대 여럿이 여기서 끝났다.\n모래에 반쯤 묻힌 뼈와 물통들.": "More than one expedition ended here. Bones and waterskins, half-buried in sand.",
	"원정대 이름": "Expedition name",
	"원정대를 꾸린다": "Form the expedition",
	"원정을 떠난다": "Set out",
	"원정이 끝난 자리. 지나는 이가 기릴 수 있다.": "Where an expedition ended. Those who pass may mourn them.",
	"위": "up",
	"위치/타이밍": "Position and timing",
	"위험": "danger",
	"위험 구역": "Danger zone",
	"위험하다, 둔다": "Too risky, leave it",
	"위험하다, 지나친다": "Too risky, pass it by",
	"유품지기": "Memento keeper",
	"유품지기가 마을에 왔다.\n\"두고 가는 법을 아는 사람은 드물지.\"": "The memento keeper has come to the village. \"Few people know how to leave a thing behind.\"",
	"음악 Suno · 효과음 ElevenLabs · AI 생성\n일부 효과음 freesound.org (CC0)": "Music by Suno · Sound effects by ElevenLabs · AI-generated\nSome sound effects from freesound.org (CC0)",
	"의견 보내기": "Send feedback",
	"이": " here",
	"이 세계를 지울까": "Erase this world?",
	"이 악물고 계속 간다": "Grit your teeth and keep going",
	"이 악물고 뚫는다": "Grit your teeth and push through",
	"이 악물고 버틴다": "Grit your teeth and endure",
	"이 여정은 가로 화면에 맞춰져 있습니다.": "This journey is made for a landscape screen.",
	"이 자리에서 살필 수 있는 횟수. 찬 점이 남은 것.": "How many times you can still search here. The filled dots are what is left.",
	"이곳의 위협을 마주하기 전엔 떠날 수 없다": "You cannot leave until you face what waits here",
	"이룬 일": "Deeds",
	"이룬 일이 소문이 되어\n마을에 새 얼굴을 불렀다.": "Word of the deed spread, and it called a new face to the village.",
	"이름 모를 곳": "a nameless place",
	"이름 없는": "Nameless",
	"이름 없는 원정대": "Nameless Expedition",
	"이미 살펴 흐려진 지점.": "A spot already searched, faded now.",
	"이번 대장의 특기": "This leader's specialty",
	"이번엔 거둔다": "Gather them this time",
	"이번엔 지나친다": "Pass it by this time",
	"이야기": "Story",
	"이전 원정대가 남긴 %s.\n아직 쓸 만하다.%s": "%s, left by the expedition before. Still good to use.%s",
	"이전 원정대가 남긴 물건. 색으로 물과 식량, 장막을 나눈다.": "A thing left by a past expedition. The color tells water, food, and tarp apart.",
	"이전 원정대가 물통을 두고 갔다.\n곁의 표식: [ 또 · 봐 ]": "The expedition before left a waterskin here.\nA marker beside it: [ again · see ]",
	"이전 원정대가 사체를 묻은\n돌무더기가 물가에 남았다.\n단내가 가시고\n물빛이 한결 맑다.": "The stones where the last expedition buried the carcass still stand by the water. The sweet stink is gone, and the water runs clearer.",
	"이전 원정대가 여기 로프를 걸어뒀다.\n그대로 건넌다.": "The expedition before rigged a rope here. You cross on it.",
	"이전 원정대가 장막을 떼어간 자리.\n남은 천 조각이 바람에 떤다.\n식량 자루는 아직 있다.": "The spot where the last expedition took the tarp. A leftover scrap of cloth trembles in the wind. The food sacks are still here.",
	"이전 원정대가 천막을 떼어간 자리.\n기둥 자국과 마른 열매 몇 알만 남았다.": "The last expedition took the tent from this spot. Only pole holes and a few dried fruits remain.",
	"이전 원정대가 파 넓혀둔 샘.\n물이 더 깊이 고였다.": "A spring the last expedition dug wider. The water gathers deeper now.",
	"이전 원정대가 파 넓힌 자리에\n물이 그득 고였다.": "Water stands deep where the last expedition dug wide.",
	"이전 원정대가 파둔 구덩이가\n그대로 있다. 더 깊이 파볼까.": "The pit the last expedition dug is still here. Worth digging deeper, maybe.",
	"이정표": "Signpost",
	"이제 길을 나설 때다.  '떠난다'를 누르게.": "Time to take the road.  Go on, press 'Set out'.",
	"일대기": "Chronicle",
	"일지를 덮는다": "Close the journal",
	"잃는 것은 없다. 대신 이번 생의 남김을 여기에 쓴다.": "You lose nothing. But it uses this life's one chance to leave something behind.",
	"자국만 눈에 담고 간다": "Fix the marks in your mind and go",
	"자국이 끝난 자리를 마저 판다": "Dig on from where the marks end",
	"잠시 벗어나 따라가 본다": "Step off and follow them a while",
	"잠시 서서 너머를 본다": "Stand a moment and look beyond",
	"잠시 손을 얹었다 간다": "Rest a hand on it a moment, then go",
	"장막": "Tarp",
	"장막 치고 안전하게 간다": "Pitch the tarp and cross safely",
	"장막 치고 잦아들길 기다린다": "Pitch the tarp and wait it out",
	"장막 치고 최대한 버틴다": "Pitch the tarp and hold out as best you can",
	"장막을 걷어 내자 그 아래\n작은 신발 한 짝이 놓여 있다.\n서둘러 떠난 사람들이었다.\n돌아왔는지는 알 수 없다.": "Pulling the tarp back uncovers a single small shoe beneath. They were people who left in a hurry. Whether they made it back, there is no knowing.",
	"장막을 치고 버틴다": "Pitch the tarp and hold out",
	"장막을 펴 버틴다": "Spread the tarp and hold out",
	"장막을 펴고 드러난 것을 줍는다": "Spread the tarp and gather what's uncovered",
	"장막이 밤새 운다.\n모래가 천을 갉는 소리 사이로\n협곡 안쪽에서 다른 소리가 섞인다.\n바람인지, 아닌지.": "The tarp cries all night. Between the rasp of sand gnawing at the cloth, another sound drifts in from deep in the canyon. Wind, or not.",
	"잦아들 때까지 듣고 있는다": "Keep listening until it dies down",
	"재앙의 자리에 선 것은\n'%s'.\n우리가 보낸 사람들이었다.": "Standing in the place of the calamity\nwas '%s'.\nThey were the people we sent.",
	"재앙의 자리엔,\n먼저 간 원정대가 서 있었다.": "In the place of the calamity\nstood an expedition that went before.",
	"잿빛": "Ashen",
	"저무는": "Waning",
	"저장 데이터 지우기": "Erase saved data",
	"저장된 이 세계를 지운다.\n원정과 흔적, 죽은 자리가 모두 사라지고\n처음부터 다시 시작한다.": "This erases the saved world. Expeditions, traces, and the places they fell will all be gone, and everything starts over from the beginning.",
	"전체 음소거": "Mute all",
	"전체 화면으로": "Go fullscreen",
	"절뚝이며 계속 간다": "Limp on",
	"정강이로 헤치며 곧장 간다": "Wade straight through, shin-deep",
	"정화천": "Filter cloth",
	"정화천에 걸러 마신다": "Strain it through the filter cloth and drink",
	"정화천에 걸러 안전하게 마신다": "Strain it through the filter cloth and drink safely",
	"정화천에 검붉은 찌꺼기가 엉겨 있다.\n이걸 거르지 못한 채 마시고\n웅덩이 가에서 되돌아가지 못한\n이들을 생각한다.": "Dark red dregs clot on the filter cloth. You think of those who drank this unstrained, and never left the pool's edge.",
	"조각을 둔덕 위에 세워 둔다": "Stand the piece up on the mound",
	"조사": "Search",
	"조사 남음": "Searches left",
	"조심": "careful",
	"조심히 타 넘는다": "Climb over with care",
	"조용한": "Quiet",
	"조작": "Controls",
	"조작 안내": "How to play",
	"조작 안내 다시보기": "Show how to play again",
	"좁은 바위 협곡.\n위쪽 돌들이 아슬아슬하게 얹혀 있다.\n잘못 건드리면 쏟아진다.": "A narrow rock gorge. The stones above rest barely balanced. One wrong touch brings them down.",
	"좌판": "Stall",
	"주림에 쓰러진 소식이 그의 등을 밀었다.": "Word of those brought down by hunger pushed at his back.",
	"주림을 견딘 이": "One who endured hunger",
	"주머니": "Pouch",
	"주요 지점": "Main spot",
	"죽기 전 단 한 번,\n[color=#8a2f1b]물건 하나를 남길 수 있다.[/color]\n그만큼 잃지만\n다음 원정대가 그것을 줍는다.\n무엇을 남길지가 이 여정의 마음이다.": "Once before dying, [color=#8a2f1b]you can leave one thing behind.[/color] You lose that much, but the next expedition picks it up. What you choose to leave is the heart of this journey.",
	"죽은 이들의 짐을 지켜 온 사람.\n길에 물건을 세 번쯤 두고 온\n원정대라야 믿고 함께 나선다.": "A keeper of what the dead carried. Only an expedition that has left things on the road three times or so is one they will trust and walk with.",
	"죽은 자리": "Where they fell",
	"죽음을 앞둔 이들은\n다음 원정대를 위해\n물건 하나를 남깁니다.\n건너편에서 다시 만나자는\n약속입니다.": "Those about to die\nleave one thing behind\nfor the next expedition.\nIt is a promise\nto meet again on the other side.",
	"지금 마셔 힘을 낸다": "Drink now for strength",
	"지금 원정은 돌아오지 못한다": "This expedition will not come back",
	"지금 이 원정대가 선 자리.": "Where this expedition stands now.",
	"지금은 지나친다 (다음 원정대가 거둔다)": "Pass by for now (the next expedition will take them in)",
	"지나친다": "Pass it by",
	"지난 원정 때 %s%s 나왔다": "The last expedition found %s%s",
	"지난 원정 때 빈손이었다": "The last expedition came up empty here",
	"지난 원정대가 밟아 이어진 길.": "A path worn in by the expeditions before.",
	"지난 원정대의 야영지.\n천막이 모래에 반쯤 묻혔다.\n한 곳만 뒤질 시간이 있다.": "A past expedition's camp. Its tent lies half-buried in sand. There is time to search one spot, no more.",
	"지난 원정도 여기를 살폈다": "The last expedition looked here too",
	"지난 원정에서 뒤처져 기다린다. 물을 나누면 거둘 수 있다.": "Left behind by a past expedition, waiting. Share water to take them in.",
	"지난 원정은 %s에서 멈췄다.\n돌아온 사람은 없다.": "The last expedition stopped at %s.\nNo one came back.",
	"지난 원정은 길 위에서 멈췄다.\n돌아온 사람은 없다.": "The last expedition stopped on the road.\nNo one came back.",
	"지난 원정은 끝에 닿았다.\n그들은 그 자리에 남았다.": "The last expedition reached the end.\nThey remained there.",
	"지난 원정의 기록": "Records of past expeditions",
	"지난번 그냥 보낸 들판.\n뼈들은 더 깊이 묻혔고,\n물통 몇은 아직 빛난다.": "The field you passed by last time. The bones lie deeper now, and a few waterskins still glint.",
	"지닌 것": "What they carry",
	"지닌 것: %s": "Carried: %s",
	"지도 · 탐험": "Map · Exploration",
	"지도로": "To the map",
	"지도에서 갈 곳을 누르면\n원정대가 나아간다.\n가 봐야 무엇이 있는지 알고,\n걸음마다 [color=#35667f]물[/color]과 [color=#8c5f16]식량[/color]이 닳는다.": "Tap a place on the map and the expedition moves out. You only learn what is there by going, and every step wears down [color=#35667f]water[/color] and [color=#8c5f16]food[/color].",
	"지도에서 갈 곳을 누르면 나아갑니다.\n가 봐야 무엇이 있는지 알 수 있고,\n걸음마다 물과 식량이 닳습니다.": "Tap a place on the map and the expedition moves out. You only learn what is there by going, and every step wears down water and food.",
	"지도의 어느 자리에도\n원정대의 발자국이 닿았다.\n어느 한 원정의 일이 아니다.": "There is no place on the map the expeditions' footprints have not touched. Not the work of any one expedition.",
	"지름길 한가운데,\n바람이 쌓아 올린 모래 둔덕이\n길을 통째로 삼켰다.\n지름길은 공짜가 아니었다.": "Halfway down the shortcut, a dune the wind has piled up has swallowed the road whole. The shortcut was not free.",
	"지름길로 간다": "Take the shortcut",
	"지운다": "Erase",
	"지워진": "Erased",
	"지체 없이 간다": "Go without delay",
	"지평선": "Horizon",
	"지평선까지 타버린 땅.\n열기가 아지랑이로 일렁이고\n그늘 한 점 없다.\n여기서부턴 아무도 없는 땅이다.": "Scorched ground clear to the horizon. Heat shimmers in the air, and there is not a scrap of shade. From here on, no one is left in this land.",
	"진흙에 손자국을 꾹 눌러 둔다": "Press a handprint deep into the mud",
	"짐꾼": "Porter",
	"짐꾼이 마을에 왔다.\n\"질 수 있는 만큼이 아니라,\n져야 하는 만큼 지는 거요.\"": "The porter has come to the village. \"You don't carry what you can. You carry what you must.\"",
	"짐을 진 이": "One who bore the load",
	"짐을 하나씩 옮기며 천천히 지난다": "Carry the packs across one at a time",
	"집는다": "Take it",
	"차단": "Blockage",
	"차례": "Contents",
	"참고 지나친다": "Hold out and pass by",
	"창 화면으로": "Leave fullscreen",
	"천막": "Tent",
	"천막 곁 나무 궤짝이\n모래에 반쯤 묻혀 있다.\n뚜껑이 모래 무게에 눌려\n땡볕에 한참을 파내야 한다.": "A wooden chest sits beside the tent, half-buried. Sand weighs the lid down; digging it free means a long while in the blazing sun.",
	"천막을 파낸다": "Dig out the tent",
	"천으로 대충 묶고 간다": "Tie them off with cloth and go",
	"천으로 코와 입을 감싸고 천천히 간다": "Wrap nose and mouth in cloth and go slow",
	"천을 둘러쓰고 천천히 간다": "Drape a cloth over your head and go slow",
	"천을 적셔 두르고 천천히 간다": "Soak a cloth, wrap it on, and go slow",
	"천을 털어 말리며 잠시 서 있는다": "Shake the cloth dry and stand a while",
	"천천히 고갈": "Drained slowly",
	"천천히 닳는 양식.": "Provisions that dwindle slowly.",
	"추위": "cold",
	"축축한 모래 속에서 물과 함께\n삭은 두레박 조각이 올라온다.\n우리보다 먼저 여기서 물을 길어 간\n사람들이 있었다.": "Up from the damp sand, along with the water, comes a piece of a rotted well bucket. There were people who drew water here before us.",
	"타이틀로 나간다": "To the title screen",
	"타이틀로 나갈까": "Leave for the title screen?",
	"탁하지만 물은 물이다.\n목이 타들어간다.\n그냥 마실지, 참을지.": "Murky, but water is water. Your throat is burning. Drink it as it is, or hold out.",
	"탁한 물": "Murky Water",
	"탁한 물 거름": "Filters murky water",
	"탁한 물 걸러 마시기.": "For straining murky water to drink.",
	"탭하여 계속": "Tap to continue",
	"탭하여 시작": "Tap to begin",
	"특기도 약점도 없다.\n어느 쪽으로도 치우치지 않은 시작.": "No strength, no weakness. A start that leans no particular way.",
	"틈 가장자리에 서서 아래를 살핀다.\n벽 중간 턱에 삭은 로프가 끊겨 있고\n그 곁에 가죽 꾸러미가 놓여 있다.\n내려가려던 이의 짐이었을까.": "You stand at the crevice's edge and look down. On a ledge partway down, a rotted rope hangs snapped, and beside it lies a leather bundle. The load, maybe, of someone who meant to go down.",
	"틈 벽에 낡은 밧줄 토막이 걸려 있다.\n몸을 기울이면 닿을 듯도 하다.": "A length of old rope hangs on the crevice wall. Lean far enough out and it might be within reach.",
	"틈 속 어둠": "Darkness in the Crevice",
	"틈 아래": "Down in the Crevice",
	"틈에 걸린 것": "Caught in the Crevice",
	"틈에 낀 배낭": "Pack in the Gap",
	"틈으로 돌아 넘는다": "Go around and cross through the gap",
	"파 넓힌 웅덩이": "Widened Pool",
	"파낸 천막엔 촘촘한 기움 자국.\n찢길 때마다 누군가 기워 온,\n오래 아껴 쓴 물건이다.\n임자는 어느 모래 밑에 있을까.": "The dug-out tent is covered in close patch-stitches. Mended every time it tore, a thing long cared for. Under which sand does its owner lie now?",
	"팔을 긁혀가며 꺼낸다": "Pull it out, scraped arms and all",
	"평범한 대장": "Ordinary leader",
	"포기한다": "Give it up",
	"폭풍": "storm",
	"폭풍 버티기.": "For holding out through a storm.",
	"폭풍 버팀": "Weathers storms",
	"폭풍 중 노출 시 사망/유실": "Exposed in the storm: death or loss",
	"폭풍 한가운데\n바람이 잠깐 멎는 눈이 보인다.\n지금뿐인 틈, 그나마 헐한 값이다.": "In the heart of the storm, an eye shows where the wind falls still for a moment. A now-or-never gap, and the cheapest way through.",
	"폭풍을 지나기 전엔 떠날 수 없다": "You cannot leave until you pass through the storm",
	"폭풍의 눈으로 달린다": "Run for the eye of the storm",
	"폭풍의 문": "Storm Gate",
	"폭풍이 두 기둥으로 서서\n문이 되었다.\n그 아래 어둠이 협곡 입구다.\n너머는 아무도 모른다.": "The storm stands as two pillars and makes a gate. The dark beneath them is the canyon mouth. What lies beyond, no one knows.",
	"폭풍이 지나가고\n모래가 가라앉으면,\n재앙을 멈추러\n원정대가 떠납니다.": "When the storm passes\nand the sand settles,\nan expedition sets out\nto stop the calamity.",
	"폭풍이 지날 때마다 원정대가 떠나고, 거의 다 죽는다.\n죽기 전 단 한 번, 다음 원정대에게 물건을 남긴다.": "Each time the storm passes, an expedition sets out, and almost all of them die.\nOnce before dying, they leave one thing for the next expedition.",
	"표시된 곳을 눌러 살핀다": "Tap a marked spot to look around",
	"표시된 곳을 눌러 살핀다  (마을에선 아무 일도 없다)": "Tap a marked spot to look around  (nothing happens in the village)",
	"표식": "Marker",
	"표식 읽기": "Reading the marks",
	"품을 들여 깃대를 다시 세운다": "Take the time to raise the flagpole again",
	"품을 들여 바닥을 판다": "Take the time and dig the bed",
	"품이 아깝다, 곧장 간다": "Not worth the labor, go straight on",
	"한 모금 아껴 담아 둔다": "Set one mouthful aside",
	"한 사람이 행렬에 들어선다.\n행렬은 %d명이 되었다.": "One more steps into the column. The column is now %d strong.",
	"한때 강이 흐르던 자리.\n바닥이 쩍쩍 갈라졌다.\n물이 숨어 있을 자리다.\n파 올리는 데 품이 든다.": "A river ran here once. The bed has cracked wide open. Water should still be hiding below. Digging it up takes work.",
	"함정": "trap",
	"해가 정수리를 두드린다.\n그늘 한 점 없다.\n잠깐 쉴지 계속 밀어붙일지.": "The sun hammers on the crown of your head. Not a scrap of shade. Rest a moment, or keep pushing.",
	"해가 지자 모래가 얼어붙는다.\n이가 딱딱 부딪히고 손끝이 곱는다.\n불 없이는 뼛속까지 갉히는 밤이다.": "When the sun goes down, the sand freezes over. Teeth chatter and fingertips stiffen. Without a fire, this night will gnaw to the bone.",
	"해거름까지 기다렸다 지난다": "Wait for dusk, then cross",
	"행렬": "Column",
	"행렬 가운데에 자리를 내준다": "Make them a place in the middle of the column",
	"행렬의 한 사람이 일어나지 못했다.": "One of the column did not get up.",
	"행적": "Record",
	"험지 통과": "Crosses rough ground",
	"협곡 벽이 삭아 내린다.\n발밑에서 돌이 쏟아지고,\n길이 무너지는 소리가 뒤를 쫓는다.\n내달리는 쪽은 숨이 타고,\n고르는 쪽은 해가 진다.": "The gorge walls are rotting away. Stones spill underfoot, and the sound of the path collapsing follows behind you. Run, and your breath burns. Pick your footing, and the sun goes down.",
	"협곡 입구를 폭풍이 가로막았다.\n모래가 살을 벤다.\n여태 지나온 어느 폭풍보다 사납다.": "A storm bars the canyon mouth. The sand cuts skin. Fiercer than any storm crossed so far.",
	"혹시 몰라 다가가 본다": "Go closer, just in case",
	"홀로 선": "Lone",
	"화면": "Screen",
	"화면 크기": "Screen size",
	"효과음": "Sound effects",
	"흩어진 것을 주워 담는다": "Gather up what's scattered",
	"흩어진 물통": "Scattered Waterskins",
}
